# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e7d767b7ef42e0182b25bc3f900defe5f4c2190261a123e0a48e07f894edbd608e3aaa3c09ea08bbe458637d44feff66c9b5e94c59ebe8f67745c2d4be9c4f1

test:
  secret_key_base: 92d094a289cb2b79fdcdd52fcacc57d8d5289729995413d08f693c13567864b434b6fc2a70d29cef20ccd568e3babfba5160de808b2647b1b60c40438cfbeae0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
